# The Docker Config version. Do not change.
version: "3.1"

services:

  client:
    image: miniapp1-client
    container_name: client
    build: ./client
    volumes:
      - "./client:/app"
    ports: 
      - "1337:3000"
    networks:
      - appnet
    depends_on:
      - server

  server:
    image: miniapp1-server
    container_name: server
    build: ./server
    volumes:
      - "./server:/app"
    ports: 
      - "3001:3001"
    networks:
      - appnet
    environment:
      DB_CONNECTION_STRING: postgresql://postgres:miniapp1pwd@db:5432/miniapp1

  db:
    image: miniapp1-db
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miniapp1pwd
      POSTGRES_DB: miniapp1

    networks:
      - appnet

networks:
  appnet:
    driver: bridge
